eval "rm -rf 3rdparty && mkdir 3rdparty && cd 3rdparty"
eval "curl -O https://www.antlr.org/download/antlr-4.8-complete.jar"
eval "cd .."
eval "antlr4='java -jar 3rdparty/antlr-4.8-complete.jar'"
eval "virtualenv --python=python3 env"
eval "source env/bin/activate"
eval "pip install -r requirements.txt"
eval "$antlr4 -visitor pryst/generated/Pryst.g4"
eval "pip install ."
eval "pryst examples/print.pst"
